//! Repository map — combine a static file tree (generated by code, exact)
//! with per-file summaries (LLM) into a single compressed `_map.md`.
//!
//! The file tree is deterministic and never goes through the LLM, so it stays
//! authoritative. The LLM only adds semantic structure (modules, dependencies)
//! on top of it.

use std::path::Path;

use crate::agent::{AgentResponse, Client, UsageInfo};
use crate::scanner::FileEntry;
use rig_core::completion::request::CompletionRequest;
use rig_core::OneOrMany;

const MAP_SYSTEM_PROMPT: &str = "\
You are building a \"repository map\": a single compressed overview of an entire code repository.

You receive two inputs:
1. A static file tree (JSON) — authoritative and exact. It lists every scanned file with its byte size. Treat it as ground truth for what exists.
2. Per-file summaries — structured notes for the extracted files (public API, imports, purpose, key details).

Produce a single Markdown document:

# Repository Map

## Purpose
1-2 sentences: what this repository does overall.

## Modules
Group files into logical systems/modules (NOT by directory layout). For each:
### <module name>
- Files: `path`, `path`, ...
- Responsibility: 1-2 sentences
- Key symbols: important public functions/types and what they do
- External dependencies: key third-party packages it relies on

## Dependencies
Directed relationships between the modules above (who depends on whom). Keep it brief.

Rules:
- File paths must come from the file tree or the summaries — never invent them.
- The file tree is authoritative: you may mention a file that has no summary by its path, but never fabricate its contents.
- Adapt to the project's actual shape: describe package/module structure for libraries, entry points for applications/CLIs, and so on. Do not force any language- or framework-specific template.
- Be a faithful aggregation of the summaries; do not invent facts absent from them.
- Do NOT propose page splits or documentation structure — only objective facts.
- Write the map in English.
- Output ONLY the Markdown, no preamble.";

/// Insert one file path into the nested JSON tree. `parts` is the path split
/// on `/`; the last part is the file leaf, intermediate parts are directories.
fn insert_path(root: &mut serde_json::Map<String, serde_json::Value>, parts: &[&str], size: u64) {
    if parts.len() == 1 {
        root.insert(parts[0].to_string(), serde_json::json!(size));
        return;
    }
    let dir = parts[0];
    let entry = root
        .entry(dir.to_string())
        .or_insert_with(|| serde_json::json!({}));
    let child = entry
        .as_object_mut()
        .expect("directory node must be an object");
    insert_path(child, &parts[1..], size);
}

/// Build a compact JSON tree from the scanned file list. Directory nodes are
/// objects; file leaves are byte sizes. Deterministic, no LLM involved.
pub fn build_tree(repo_root: &Path, files: &[FileEntry]) -> String {
    let mut root = serde_json::Map::new();
    for f in files {
        let size = std::fs::metadata(repo_root.join(&f.relative_path))
            .map(|m| m.len())
            .unwrap_or(0);
        let parts: Vec<&str> = f.relative_path.split('/').collect();
        insert_path(&mut root, &parts, size);
    }
    serde_json::Value::Object(root).to_string()
}

/// Recursively collect all `*.summary.md` files under `dir`, keyed by their
/// path relative to `root` (forward slashes), sorted by relative path.
fn collect_summaries(root: &Path, dir: &Path) -> std::io::Result<Vec<(String, String)>> {
    let mut out = Vec::new();
    collect_summaries_rec(root, dir, &mut out)?;
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

fn collect_summaries_rec(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, String)>,
) -> std::io::Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_summaries_rec(root, &path, out)?;
        } else {
            let is_summary = path
                .file_name()
                .and_then(|s| s.to_str())
                .map(|s| s.ends_with(".summary.md"))
                .unwrap_or(false);
            if is_summary {
                let rel = path
                    .strip_prefix(root)
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .replace('\\', "/");
                let content = std::fs::read_to_string(&path)?;
                out.push((rel, content));
            }
        }
    }
    Ok(())
}

/// Aggregate the static file tree and all per-file summaries under `scan_dir`
/// into a single map, written to `map_path`. Returns (prompt_tokens,
/// completion_tokens). The LLM is not given a max_tokens cap, so the map is
/// never truncated mid-way.
pub async fn generate_map(
    client: &Client,
    model: &str,
    repo_root: &Path,
    files: &[FileEntry],
    scan_dir: &Path,
    map_path: &Path,
) -> anyhow::Result<(u32, u32)> {
    let tree = build_tree(repo_root, files);

    let summaries = collect_summaries(scan_dir, scan_dir)?;
    if summaries.is_empty() {
        anyhow::bail!("no summaries found under {}", scan_dir.display());
    }

    let mut user_msg = String::new();
    user_msg.push_str("Repository file tree (static scan, authoritative):\n");
    user_msg.push_str(&tree);
    user_msg.push_str("\n\nPer-file summaries:\n\n");
    for (rel, content) in &summaries {
        user_msg.push_str(&format!("--- {} ---\n{}\n\n", rel, content));
    }

    let request = CompletionRequest {
        model: Some(model.to_string()),
        chat_history: OneOrMany::many(vec![
            rig_core::completion::Message::system(MAP_SYSTEM_PROMPT),
            rig_core::completion::Message::user(&user_msg),
        ])
        .expect("chat_history must not be empty"),
        preamble: None,
        tools: vec![],
        tool_choice: None,
        max_tokens: None,
        temperature: Some(0.1),
        additional_params: None,
        documents: vec![],
        output_schema: None,
        record_telemetry_content: false,
    };

    let response: AgentResponse = client.completion(request).await?;

    let map_md = response.text.unwrap_or_else(|| "(no output)".to_string());
    let usage = response.usage.unwrap_or(UsageInfo {
        prompt_tokens: 0,
        completion_tokens: 0,
    });

    std::fs::write(map_path, &map_md)?;

    Ok((usage.prompt_tokens, usage.completion_tokens))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn write_summary(scan: &Path, rel: &str, content: &str) {
        let path = scan.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, content).unwrap();
    }

    #[test]
    fn builds_compact_json_tree_with_sizes() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        fs::create_dir_all(root.join("src/tools")).unwrap();
        fs::write(root.join("Cargo.toml"), "[package]").unwrap();
        fs::write(root.join("src/main.rs"), "fn main() {}").unwrap();
        fs::write(root.join("src/tools/mod.rs"), "").unwrap();

        let files = vec![
            FileEntry { relative_path: "Cargo.toml".into() },
            FileEntry { relative_path: "src/main.rs".into() },
            FileEntry { relative_path: "src/tools/mod.rs".into() },
        ];

        let tree = build_tree(root, &files);
        let v: serde_json::Value = serde_json::from_str(&tree).unwrap();
        assert_eq!(v["Cargo.toml"], "[package]".len() as u64);
        assert_eq!(v["src"]["main.rs"], "fn main() {}".len() as u64);
        assert_eq!(v["src"]["tools"]["mod.rs"], 0);
    }

    #[test]
    fn collects_and_sorts_summaries() {
        let tmp = tempfile::tempdir().unwrap();
        let scan = tmp.path().join("_scan");
        write_summary(&scan, "src/main.rs.summary.md", "main summary");
        write_summary(&scan, "Cargo.toml.summary.md", "manifest summary");

        let summaries = collect_summaries(&scan, &scan).unwrap();
        assert_eq!(summaries.len(), 2);
        // Sorted by relative path: "Cargo.toml.summary.md" < "src/main.rs.summary.md"
        assert_eq!(summaries[0].0, "Cargo.toml.summary.md");
        assert_eq!(summaries[1].0, "src/main.rs.summary.md");
        assert_eq!(summaries[0].1, "manifest summary");
    }

    #[tokio::test]
    async fn generates_map_from_summaries() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path();
        fs::create_dir_all(repo.join("src")).unwrap();
        fs::write(repo.join("src/main.rs"), "fn main() {}").unwrap();
        let scan = repo.join("_scan");
        write_summary(&scan, "src/main.rs.summary.md", "# src/main.rs\n\n## Purpose\nentry point");

        let map_path = repo.join("_map.md");
        let files = vec![FileEntry { relative_path: "src/main.rs".into() }];

        let client = Client::mock(vec![AgentResponse {
            text: Some("# Repository Map\n\n## Purpose\ntest repo".to_string()),
            tool_calls: vec![],
            prefix_contents: vec![],
            usage: Some(UsageInfo {
                prompt_tokens: 100,
                completion_tokens: 20,
            }),
        }]);

        let (prompt, completion) =
            generate_map(&client, "m", repo, &files, &scan, &map_path).await.unwrap();
        assert_eq!((prompt, completion), (100, 20));

        let written = fs::read_to_string(&map_path).unwrap();
        assert!(written.contains("Repository Map"));
    }

    #[tokio::test]
    async fn errors_on_empty_scan_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path();
        let scan = repo.join("_scan");
        fs::create_dir_all(&scan).unwrap();
        let map_path = repo.join("_map.md");
        let files: Vec<FileEntry> = vec![];
        let client = Client::mock(vec![]);

        let err = generate_map(&client, "m", repo, &files, &scan, &map_path).await.unwrap_err();
        assert!(err.to_string().contains("no summaries found"));
    }
}
